syntax = "proto3";

package user;

// This option tells the compiler where to put the generated Go files
option go_package = "./proto";

service UserService {
  // Used to check if a single user exists (for 1:1 chats)
  rpc GetUser (GetUserRequest) returns (GetUserResponse);

  // Used to check if multiple users exist (for Group chats)
  rpc CheckUsersExist (CheckUsersExistRequest) returns (CheckUsersExistResponse);
}

// --- Messages for GetUser ---
message GetUserRequest {
  int64 id = 1;
}

message GetUserResponse {
  int64 id = 1;
  string username = 2;
  string email = 3;
  string avatar_url = 4;
}

// --- Messages for CheckUsersExist ---
message CheckUsersExistRequest {
  repeated int64 user_ids = 1;
}

message CheckUsersExistResponse {
  bool exists = 1;
}