basePath: /
host: localhost:8082
info:
  contact: {}
  description: API для работы с чатами, сообщениями и файлами (MinIO).
  title: Chat Service API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
